<!-- Portfolio -->
<div class="portfolio">
	<?php if (count($this->items) > 1): ?><a class="prev browse left" title="<?php echo Aitsu_Translate::_("zur&uuml;ck"); ?>"></a> <a class="next browse right" title="<?php echo Aitsu_Translate::_("weiter"); ?>"></a><?php endif; ?>
	<div class="scrollable">
		<div class="items">

		<?php $maxHeight = 0; ?>
		<?php foreach ($this->items as $index=>$item) : ?>

			<?php
			// set the dimensions according to your layout
			$imgWidth = 270;

			// get dimensions of original file
			$img = 'application/data/media/'.$item->idart.'/'.$item->mediaid.'.'.$item->extension;
			$imgDim = getimagesize($img);
			$factor = $imgWidth/$imgDim[0];
			$imgHeight = round($imgDim[1]*$factor);

			if ($maxHeight < $imgHeight) {
				$maxHeight = $imgHeight;
			}

			// get alt-text for image
			$alt = false;
			if($item->description != '') {
				$alt = $item->description;
			} elseif($item->subline != '') {
				$alt = $item->subline;
			} elseif($item->name != '') {
				$alt = $item->name;
			}
			?>

			<div class="item">
				<div class="subcl">
					<img alt="<?php echo $item->subline; ?>" src="/image/270/600/0/<?php echo $item->idart; ?>/<?php echo $item->mediaid; ?>.<?php echo $item->extension; ?>" />
				</div>
				<div class="subcr">
					<h3><?php echo strip_tags(htmlentities($item->subline, ENT_COMPAT, 'utf-8')); ?></h3>
					<p><?php echo nl2br(htmlentities($item->description, ENT_COMPAT, 'utf-8')); ?></p>
				</div>
			</div>

		<?php endforeach; ?>

		</div>
	</div>
</div>

<?php
if (count($this->items) > 1) {
Aitsu_Util_Javascript :: add("
$(document).ready(function() {
	$('.scrollable').scrollable({mousewheel: true, speed: 750}).autoscroll({interval: 5000}).css({height:'".$maxHeight."px'});
});
");
}
?>