<script type="application/x-aitsu" src="Text:Headline1">
	tag = h1
</script>
<script type="application/x-aitsu" src="HTML:HTML_Article"></script>
<script type="application/x-aitsu" src="ContactForm:Feedback">
    template = "feedback"

    field.Nachname.show = 1
    field.Nachname.validation = NoTags
    field.Nachname.required = 1

    field.Vorname.show = 1
    field.Vorname.validation = NoTags
    field.Vorname.required = 1

    field.Firma.show = 1
    field.Firma.validation = NoTags
    field.Firma.required = 0

    field.Strasse.show = 1
    field.Strasse.validation = NoTags
    field.Strasse.required = 1

    field.PLZ.show = 1
    field.PLZ.validation = NoTags
    field.PLZ.required = 1

    field.Ort.show = 1
    field.Ort.validation = NoTags
    field.Ort.required = 1

    field.Land.show = 1
    field.Land.validation = NoTags
    field.Land.required = 0

    field.Telefon.show = 1
    field.Telefon.validation = NoTags
    field.Telefon.required = 1

    field.Email.show = 1
    field.Email.validation = Email
    field.Email.required = 0

    field.Betreff.show = 1
    field.Betreff.validation = NoTags
    field.Betreff.required = 1

    field.Message.show = 1
    field.Message.validation = NoTags
    field.Message.required = 1
</script>
<script type="application/x-aitsu" src="HTML:Col1_2"></script>