<!-- Illustrationen mit Slideshow -->
<div class="image_container">
	<?php foreach($this->images as $image): ?>

		<?php
		// set the dimensions according to your layout
		$imgWidth = $this->imgWidth;
		$imgHeight = $this->imgHeight;

		// get dimensions of original file
		$img = 'application/data/media/'.$image->idart.'/'.$image->mediaid.'.'.$image->extension;
		$imgDim = getimagesize($img);

		if ($imgWidth >= $imgHeight) {
			// constant width
			$factor = $imgWidth/$imgDim[0];
			$imgHeight = round($imgDim[1]*$factor);
		} else {
			// constant height
			$factor = $imgHeight/$imgDim[1];
			$imgWidth = round($imgDim[0]*$factor);
		}

		// get alt-text for image
		$alt = false;
		if($image->description != '') {
			$alt = $image->description;
		} elseif($image->subline != '') {
			$alt = $image->subline;
		} elseif($image->name != '') {
			$alt = $image->name;
		}
		?>
			
		<div class="item">
			<img src="/image/<?php echo $imgWidth; ?>/<?php echo $imgHeight; ?>/2/<?php echo $image->idart; ?>/<?php echo $image->filename; ?>" alt="<?php echo $alt; ?>" width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>"/>
			<?php if($alt): ?>
				<p class="caption"><?php echo $alt; ?></p>
			<?php endif; ?>
		</div>
	<?php endforeach; ?>
</div>

<?php
if (count($this->images) > 1) {
Aitsu_Util_Javascript :: add("
$(document).ready(function() {
	$('.image_container').cycle({
        fx:     'fade',
        speed:  'fast',
        next: '.image_container',
        timeout: 5000
	});
});
");
}
?>