<!-- klein -->
<div class="image_container zertifizierungen">
	<?php foreach($this->images as $image): ?>

		<?php
		$alt = $image->filename;
		if($image->description != '') {
			$alt = $image->description;
		} elseif($image->subline != '') {
			$alt = $image->subline;
		} elseif($image->name != '') {
			$alt = $image->name;
		}
		?>
			
		<img src="/image/192/192/2/<?php echo $image->idart; ?>/<?php echo $image->filename; ?>" alt="<?php echo $alt; ?>" />
	<?php endforeach; ?>
</div>