<!-- P & DL -->
<div class="image_list pdl">
<?php $i = 0; ?>
<?php foreach($this->items as $index=>$article): ?>
    <div class="item<?php if($i == 0): ?> first<?php endif; ?>">
		<?php if(!empty($article->image)): ?>
			<a href="{ref:idart-<?php echo $article->idart; ?>}" title="<?php echo $article->pagetitle;?>" class="image_container">
				<img src="/image/150/100/2/<?php echo $article->idart; ?>/<?php echo $article->image; ?>" alt="<?php echo $article->articletitle; ?>" class="float_left"/>
			</a>
		<?php endif; ?>
        <p class="caption">
            <?php if(!empty($article->pagetitle)): ?><span class="name"><?php echo $article->pagetitle; ?></span><?php endif; ?>
        </p>
    </div>
    <?php $i++; ?>
<?php endforeach; ?>
</div>