<div class="subcolumns">
	<div class="c50l">
		<div class="subcl">
			<script type="application/x-aitsu" src="HTML:Main_left"></script>
		</div>
	</div>
	<div class="c25l">
		<div class="subc">
			<script type="application/x-aitsu" src="HTML:Main_right"></script>
		</div>
	</div>
	<div class="c25r">
		<div class="subcr">
			<div class="info">
				<script type="application/x-aitsu" src="Template:Infobox">
              		defaultTemplate = news
              		
              		template.news.name = News (Standard)
              		template.news.file = templates/maincontent/news-in-infobox.phtml
              		
              		template.html.name = HTML
              		template.html.file = templates/maincontent/html-in-infobox.phtml

              		template.nzz.name = NZZ Headlines
              		template.nzz.file = templates/maincontent/nzz-news-in-infobox.phtml
              	</script>
			</div>
		</div>
	</div>
</div>