        <div class="subcolumns">
          <div class="c75l">
            <div class="subcl">
              <script type="application/x-aitsu" src="HTML:Main_left"></script>
              <script type="application/x-aitsu" src="Address:Person"></script>
            </div>
          </div>
          <div class="c25r">
            <div class="subcr">
              <!-- Insert your subtemplate content here -->
              <div class="info">
              	<script type="application/x-aitsu" src="Template:Infobox">
              		defaultTemplate = news
              		
              		template.news.name = News (Standard)
              		template.news.file = templates/maincontent/news-in-infobox.phtml
              		
              		template.html.name = HTML
              		template.html.file = templates/maincontent/html-in-infobox.phtml
              	</script>
              </div>
            </div>
          </div>
        </div>