<div class="subcolumns">
	<div class="c50l">
		<div class="subcl">
			<script type="application/x-aitsu" src="HTML:Main_left"></script>
			<script type="application/x-aitsu" src="ContactForm:form">
				template = yaml
			
				field.Firstname.show = 1
				field.Firstname.maxlength = 100
				field.Firstname.required = 1
							
				field.Lastname.show = 1
				field.Lastname.maxlength = 100
				field.Lastname.required = 1
						
				field.Company.show = 1
				field.Company.maxlength = 255
				field.Company.required = 0
							
				field.Division.show = 0
						
				field.Street.show = 1
				field.Street.maxlength = 100
				field.Street.required = 0
							
				field.Zip.show = 1
				field.Zip.maxlength = 30
				field.Zip.required = 1
							
				field.City.show = 1
				field.City.maxlength = 255
				field.City.required = 1
							
				field.Country.show = 0
						
				field.Phone.show = 1
				field.Phone.maxlength = 30
				field.Phone.required = 1
					
				field.Fax.show = 0
							
				field.Email.show = 1
				field.Email.maxlength = 255
				field.Email.required = 1
				field.Email.validation = Email
						
				field.Message.show = 1
				field.Message.maxlength = 4000
				field.Message.required = 0
			</script>
		</div>
	</div>
	<div class="c25l">
		<div class="subc">
			<script type="application/x-aitsu" src="HTML:Main_right"></script>
		</div>
	</div>
	<div class="c25r">
		<div class="subcr">
			<div class="info">
				<script type="application/x-aitsu" src="Template:Infobox">
	           		defaultTemplate = news
	             		
	           		template.news.name = News (Standard)
	           		template.news.file = templates/maincontent/news-in-infobox.phtml
	             		
	           		template.html.name = HTML
	           		template.html.file = templates/maincontent/html-in-infobox.phtml
	           	</script>
			</div>
		</div>
	</div>
</div>
