<!-- Zitat -->
<?php if (count($this->items) > 0): ?>
<div class="quotes">
	<?php if (count($this->items) > 1): ?><a class="prev browse left" title="<?php echo Aitsu_Translate::_("zur&uuml;ck"); ?>"></a> <a class="next browse right" title="<?php echo Aitsu_Translate::_("weiter"); ?>"></a><?php endif; ?>
	<div class="scrollable">
		<div class="items">

		<?php foreach ($this->items as $index=>$item) : ?>

			<?php
			// set the dimensions according to your layout
			$imgWidth = 176;

			// get dimensions of original file
			$img = 'application/data/media/'.$item->idart.'/'.$item->mediaid.'.'.$item->extension;
			$imgDim = getimagesize($img);
			$factor = $imgWidth/$imgDim[0];
			$imgHeight = round($imgDim[1]*$factor);

			// get alt-text for image
			$alt = false;
			if(!empty($item->name)) {
				$alt = $item->name;
			}
			if(!empty($item->subline)) {
				$alt .= $item->subline;
			}
			?>

			<div class="item">
			
    			<img alt="<?php echo $alt; ?>" src="/image/176/264/2/<?php echo $item->idart; ?>/<?php echo $item->mediaid; ?>.<?php echo $item->extension; ?>" />

			<?php if(!empty($item->name)): ?>
	    		<h2><?php echo strip_tags(htmlentities($item->name, ENT_COMPAT, 'utf-8')); ?></h2>
			<?php endif; ?>

			<?php if(!empty($item->subline)): ?>
		    	<h3><?php echo strip_tags(htmlentities($item->subline, ENT_COMPAT, 'utf-8')); ?></h3>
			<?php endif; ?>

			<?php if(!empty($item->description)): ?>
		        <p><?php echo nl2br(htmlentities($item->description, ENT_COMPAT, 'utf-8')); ?></p>
			<?php endif; ?>

			</div>

		<?php endforeach; ?>

		</div>
	</div>
</div>
<?php endif; ?>

<?php
if (count($this->items) > 1) {
Aitsu_Util_Javascript :: add("
$(document).ready(function() {
    var maxHeight = 0;
    $('.items .item').each(function(){
        var thisHeight = $(this).height();
        maxHeight = Math.max(thisHeight, maxHeight);
    });
	$('.scrollable').scrollable({circular: true, mousewheel: true, speed: 750}).autoscroll({interval: 5000}).height(maxHeight);
});
");
}
?>