<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<script type="application/x-aitsu" src="PageTitle">
	suffix = "&nbsp;&middot; Stiftung B&auml;chtelen"
</script>
<script type="application/x-aitsu" src="HTML.Meta.Tags"></script>
<script type="application/x-aitsu" src="HTML.Meta.CanonicalTag"></script>
<script type="application/x-aitsu" src="HTML.Meta.ResourceBundle:CSS">
	type = css
	res.1 = /yaml/core/base.css
	res.2 = /yaml/screen/forms.css
	res.3 = /css/screen/basemod.css
	res.4 = /fonts/webfonts.css
	res.5 = /css/screen/content.css
	res.6 = /css/screen/colors.css
	res.7 = /yaml/print/print_120_draft.css
	res.8 = /css/print/print.css
    res.9 = /plugins/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.css
	res.10 = /css/screen/forms.css
</script>
<script type="application/x-aitsu" src="HTML.Meta.ResourceBundle:JS">
	type = js
	res.1 = /js/jquery-1.6.1.min.js
	res.2 = /yaml/core/js/yaml-focusfix.js
	res.3 = /js/jquery.tools.min.js
	res.4 = /js/baechtelen.js
    res.5 = /plugins/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.js
</script>
<!--[if lte IE 7]>
<link href="/skin/css/patches/ielte7.css" rel="stylesheet" type="text/css" />
<![endif]-->
<!--[if lte IE 8]>
<link href="/skin/css/patches/ielte8.css" rel="stylesheet" type="text/css" />
<![endif]-->