<ul id="mainnav">
	<?php foreach ($this->nav->children as $index => $mainNav) : ?>
	<li id="mn<?php echo $index; ?>"<?php if ($index == 0 && $index != count($this->nav->children)-1) : ?> class="first"<?php endif; ?><?php if ($index == count($this->nav->children)-1 && $index != 0) : ?> class="last"<?php endif; ?><?php if ($index == 0 && $index == count($this->nav->children)-1) : ?> class="first last"<?php endif; ?>>
		<?php if (!$mainNav->isparent && $mainNav->iscurrent && count($mainNav->children) == 0) : ?><strong><?php endif; ?><?php if ((count($mainNav->children) > 0 && $mainNav->iscurrent) || $mainNav->isparent) : ?><em><?php endif; ?>
		<a href="{ref:idcat-<?php echo $mainNav->idcat; ?>}"><?php echo $mainNav->name; ?></a>
		<?php if (!$mainNav->isparent && $mainNav->iscurrent && count($mainNav->children) == 0) : ?></strong><?php endif; ?><?php if ((count($mainNav->children) > 0 && $mainNav->iscurrent) || $mainNav->isparent) : ?></em><?php endif; ?>
		<?php if (count($mainNav->children) > 0 && ($mainNav->iscurrent OR $mainNav->isparent) && $index != 0) : ?>
		<ul<?php if (count($mainNav->children) > 0 && $mainNav->iscurrent && !$mainNav->isparent) : ?> class="ischild"<?php endif; ?>>
			<?php foreach ($mainNav->children as $index=>$subNav) : ?>
			<li<?php if ($index == 0 && $index != count($mainNav->children)-1) : ?> class="first"<?php endif; ?><?php if ($index == count($mainNav->children)-1 && $index != 0) : ?> class="last"<?php endif; ?><?php if ($index == 0 && $index == count($mainNav->children)-1) : ?> class="first last"<?php endif; ?>>
				<?php if (!$subNav->isparent && $subNav->iscurrent && count($subNav->children) == 0) : ?><strong><?php endif; ?><?php if ((count($subNav->children) > 0 && $subNav->iscurrent) || $subNav->isparent) : ?><em><?php endif; ?>
				<a href="{ref:idcat-<?php echo $subNav->idcat; ?>}"><?php echo $subNav->name; ?></a>
				<?php if (!$subNav->isparent && $subNav->iscurrent && count($subNav->children) == 0) : ?></strong><?php endif; ?><?php if ((count($subNav->children) > 0 && $subNav->iscurrent) || $subNav->isparent) : ?></em><?php endif; ?>
			</li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
	</li>
	<?php endforeach; ?>
</ul>