<!-- Allgemeine Liste (CDs etc.) -->
<div class="cds">
<?php $i = 0; ?>
<?php foreach($this->items as $index=>$article): ?>
    <div class="item<?php if($i == 0): ?> first<?php endif; ?>">
        <h2 class="title">
	        <a href="{ref:idart-<?php echo $article->idart; ?>}" title="<?php echo $article->pagetitle;?>">
	        <?php echo $article->pagetitle;?></a>
        </h2>
        <?php if (isset($article->teasertitle)): ?>
		    <h3 class="subtitle">
			    <a href="{ref:idart-<?php echo $article->idart; ?>}" title="<?php echo $article->pagetitle;?>">
			       <?php echo $article->teasertitle;?>
			    </a>
		    </h3>
        <?php endif; ?>
		<?php if(!empty($article->image)): ?>
			<a href="{ref:idart-<?php echo $article->idart; ?>}" title="<?php echo $article->pagetitle;?>" class="image_container">
				<img src="/image/150/150/0/<?php echo $article->idart; ?>/<?php echo $article->image; ?>" alt="<?php echo $article->articletitle; ?>" class="float_left"/>
			</a>
		<?php endif; ?>
	    <?php if (isset($article->summary)): ?>
	        <p>
		        <?php echo nl2br($article->summary); ?>
		        <a href="{ref:idart-<?php echo $article->idart; ?>}" title="<?php echo $article->pagetitle;?>">
			    <?php echo Aitsu_Translate::_("weiter"); ?>
		        </a>
	        </p>
        <?php endif; ?>
    </div>
    <?php $i++; ?>
<?php endforeach; ?>
</div>