     <div id="main">
      <div id="col1" role="main">
        <div id="col1_content" class="clearfix">
			<script type="application/x-aitsu" src="Template:Buehne">
           		defaultTemplate = stdarticle
             		
				template.stdarticle.name = Artikel (Standard)
              	template.stdarticle.file = templates/maincontent/col1/stdarticle.phtml

				template.calendar.name = Kalender
              	template.calendar.file = templates/maincontent/col1/calendar.phtml

				template.news.name = News
              	template.news.file = templates/maincontent/col1/news.phtml

				template.gallery.name = Galerie (Bilderblock)
              	template.gallery.file = templates/maincontent/col1/gallery.phtml

				template.portfolio.name = Portfolio-Slideshow
              	template.portfolio.file = templates/maincontent/col1/portfolio.phtml

                template.productsnservices.name = Produkte & Dienstleistungen
                template.productsnservices.file = templates/maincontent/col1/productsnservices.phtml

				template.feedback.name = Feedback-Formular
              	template.feedback.file = templates/maincontent/col1/feedback.phtml
			</script>
			<script type="application/x-aitsu" src="SetLinkToArticle:SetLink">
				tag.0 = news
                tag.1 = aktuell
                tag.2 = Kalender
			</script>
        </div>
      </div>
      <div id="col2" role="complementary">
        <div id="col2_content" class="clearfix">
			<script type="application/x-aitsu" src="Template:rechte_Spalte">
           		defaultTemplate = default

				template.default.name = Headline und Editor (Standard)
              	template.default.file = templates/maincontent/col2/default.phtml
             		
				template.testimonials.name = Testimonials
              	template.testimonials.file = templates/maincontent/col2/testimonials.phtml

				template.news.name = News
              	template.news.file = templates/maincontent/col2/news.phtml
			</script>
        </div>
      </div>
      <div id="col3" role="navigation">
        <div id="col3_content" class="clearfix">		
        <!-- LuceneStopContentStart -->
		<script type="application/x-aitsu" src="Navigation:Sub">
			idcat = 1
			template = subnav
		</script>
        <!-- LuceneStopContentEnd -->
        </div>
        <div id="ie_clearing">&nbsp;</div>
      </div>
    </div>