     <div id="main" class="hidecol2">
      <div id="col1" role="main">
        <div id="col1_content" class="clearfix">
			<script type="application/x-aitsu" src="Template:Buehne">
           		defaultTemplate = stdarticle
             		
				template.stdarticle.name = Artikel (Standard)
              	template.stdarticle.file = templates/maincontent/col1/stdarticle.phtml

				template.calendar.name = Kalender
              	template.calendar.file = templates/maincontent/col1/calendar.phtml

				template.news.name = News
              	template.news.file = templates/maincontent/col1/news.phtml

				template.gallery.name = Galerie (Bilderblock)
              	template.gallery.file = templates/maincontent/col1/gallery.phtml

				template.feedback.name = Feedback-Formular
              	template.feedback.file = templates/maincontent/col1/feedback.phtml
			</script>
			<script type="application/x-aitsu" src="SetLinkToArticle:SetLink">
				tag.0 = news
                tag.1 = aktuell
			</script>
        </div>
      </div>
      <div id="col3" role="navigation">
        <div id="col3_content" class="clearfix">
        <!-- LuceneStopContentStart -->
		<script type="application/x-aitsu" src="Navigation:Sub">
			idcat = 1
			template = subnav
		</script>
        <!-- LuceneStopContentEnd -->
        </div>
        <div id="ie_clearing">&nbsp;</div>
      </div>
    </div>