<?php foreach ($this->nav->children as $index=>$subnavigation1) : /*** ERSTES LEERES FOREACH ***/ ?>
  <?php if ($subnavigation1->isparent OR $subnavigation1->iscurrent) : /*** NUR DURCHLAUFEN, WENN ES AKTUELL ODER EIN ELTERNELEMENT IST ***/ ?>
    <?php if (count($subnavigation1->children) > 0) : /*** NUR DURCHLAUFEN, WENN ES KINDELEMENTE HAT ***/ ?>

<?php /* only display third-level-subnavigation if parent-cat is first item (= Home) */ ?>
<?php if ($index != 0) : ?>

<?php foreach ($subnavigation1->children as $subnavigation2) : /*** ZWEITES LEERES FOREACH ***/ ?>
  <?php if ($subnavigation2->isparent OR $subnavigation2->iscurrent) : /*** NUR DURCHLAUFEN, WENN ES AKTUELL ODER EIN ELTERNELEMENT IST ***/ ?>
    <?php if (count($subnavigation2->children) > 0) : /*** NUR DURCHLAUFEN, WENN ES KINDELEMENTE HAT ***/ ?>
        
    <ul id="subnav"<?php if (count($subnavigation2->children) > 0 && $subnavigation2->iscurrent && !$subnavigation2->isparent) : ?> class="issubchild"<?php endif; ?>>
      <?php foreach (array_values($subnavigation2->children) as $index => $subnavigation3) : ?>
       <li<?php if ($index == 0 && $index != count($subnavigation2->children)-1) : ?> class="first"<?php endif; ?><?php if ($index == count($subnavigation2->children)-1 && $index != 0) : ?> class="last"<?php endif; ?><?php if ($index == 0 && $index == count($subnavigation2->children)-1) : ?> class="first last"<?php endif; ?>>
          <?php if (!$subnavigation3->isparent && $subnavigation3->iscurrent && count($subnavigation3->children) == 0) : ?><strong><?php endif; ?><?php if ((count($subnavigation3->children) > 0 && $subnavigation3->iscurrent) || $subnavigation3->isparent) : ?><em><?php endif; ?>
          <a href="{ref:idcat-<?php echo $subnavigation3->idcat; ?>}"><?php echo $subnavigation3->name; ?></a>
          <?php if (!$subnavigation3->isparent && $subnavigation3->iscurrent && count($subnavigation3->children) == 0) : ?></strong><?php endif; ?><?php if ((count($subnavigation3->children) > 0 && $subnavigation3->iscurrent) || $subnavigation3->isparent) : ?></em><?php endif; ?>
          <?php if (count($subnavigation3->children) > 0 && ($subnavigation3->iscurrent OR $subnavigation3->isparent)) : ?>
          <ul>
        <?php foreach (array_values($subnavigation3->children) as $index=>$subnavigation4) : ?>
             <li<?php if ($index == 0 && $index != count($subnavigation3->children)-1) : ?> class="first"<?php endif; ?><?php if ($index == count($subnavigation3->children)-1 && $index != 0) : ?> class="last"<?php endif; ?><?php if ($index == 0 && $index == count($subnavigation3->children)-1) : ?> class="first last"<?php endif; ?>>
             <?php if (!$subnavigation4->isparent && $subnavigation4->iscurrent && count($subnavigation4->children) == 0) : ?><strong><?php endif; ?><?php if ((count($subnavigation4->children) > 0 && $subnavigation4->iscurrent) || $subnavigation4->isparent) : ?><em><?php endif; ?>
             <a href="{ref:idcat-<?php echo $subnavigation4->idcat; ?>}"><?php echo $subnavigation4->name; ?></a>
             <?php if (!$subnavigation4->isparent && $subnavigation4->iscurrent && count($subnavigation4->children) == 0) : ?></strong><?php endif; ?><?php if ((count($subnavigation4->children) > 0 && $subnavigation4->iscurrent) || $subnavigation4->isparent) : ?></em><?php endif; ?>
             </li>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        </li>
      <?php endforeach; ?>
    </ul>

    <?php endif; ?>
  <?php endif; ?>
<?php endforeach; ?>    

<?php else: ?>
<?php /* only display second-level-subnavigation if parent-cat is first item (= Home) */ ?>

	<ul id="subnav">
      <?php foreach (array_values($subnavigation1->children) as $index => $subnavigation2) : ?>
       <li<?php if ($index == 0 && $index != count($subnavigation1->children)-1) : ?> class="first"<?php endif; ?><?php if ($index == count($subnavigation1->children)-1 && $index != 0) : ?> class="last"<?php endif; ?><?php if ($index == 0 && $index == count($subnavigation1->children)-1) : ?> class="first last"<?php endif; ?>>
          <?php if (!$subnavigation2->isparent && $subnavigation2->iscurrent && count($subnavigation2->children) == 0) : ?><strong><?php endif; ?><?php if ((count($subnavigation2->children) > 0 && $subnavigation2->iscurrent) || $subnavigation2->isparent) : ?><em><?php endif; ?>
          <a href="{ref:idcat-<?php echo $subnavigation2->idcat; ?>}"><?php echo $subnavigation2->name; ?></a>
          <?php if (!$subnavigation2->isparent && $subnavigation2->iscurrent && count($subnavigation2->children) == 0) : ?></strong><?php endif; ?><?php if ((count($subnavigation2->children) > 0 && $subnavigation2->iscurrent) || $subnavigation2->isparent) : ?></em><?php endif; ?>
          <?php if (count($subnavigation2->children) > 0 && ($subnavigation2->iscurrent OR $subnavigation2->isparent)) : ?>
          <ul>
        <?php foreach (array_values($subnavigation2->children) as $index=>$subnavigation3) : ?>
             <li<?php if ($index == 0 && $index != count($subnavigation2->children)-1) : ?> class="first"<?php endif; ?><?php if ($index == count($subnavigation2->children)-1 && $index != 0) : ?> class="last"<?php endif; ?><?php if ($index == 0 && $index == count($subnavigation2->children)-1) : ?> class="first last"<?php endif; ?>>
             <?php if (!$subnavigation3->isparent && $subnavigation3->iscurrent && count($subnavigation3->children) == 0) : ?><strong><?php endif; ?><?php if ((count($subnavigation3->children) > 0 && $subnavigation3->iscurrent) || $subnavigation3->isparent) : ?><em><?php endif; ?>
             <a href="{ref:idcat-<?php echo $subnavigation3->idcat; ?>}"><?php echo $subnavigation3->name; ?></a>
             <?php if (!$subnavigation3->isparent && $subnavigation3->iscurrent && count($subnavigation3->children) == 0) : ?></strong><?php endif; ?><?php if ((count($subnavigation3->children) > 0 && $subnavigation3->iscurrent) || $subnavigation3->isparent) : ?></em><?php endif; ?>
             </li>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        </li>
      <?php endforeach; ?>
    </ul>

<?php endif; ?>

    <?php endif; ?>
  <?php endif; ?>
<?php endforeach; ?>