<!-- Datei-Auflistung auf mehreren Zeilen -->
<ul class="files downloads">
<?php
$i = 1;
foreach($this->images as $file): ?>
	<?php
	// get title-text for file
	$name = $file->filename;
	if($file->description != '') {
		$name = $file->description;
	} elseif($file->subline != '') {
		$name = $file->subline;
	} elseif($file->name != '') {
		$name = $file->name;
	}
	?>
	<li><a href="/file/download/<?php echo $file->idart; ?>/<?php echo $file->filename; ?>" title="<?php echo $name; ?>"<?php if (count($this->images) == 1): ?> class="last"<?php endif; ?>><?php echo $name; ?></a> [<?php echo strtoupper($file->extension); ?>, <?php echo Mereo_Util_File::formatBytes($file->size); ?>]</li>
<?php
$i++;
endforeach; ?>
</ul>