<!-- Galerie: Bilderblock -->
<div class="image_list pdl">
<?php

$i = 0;
foreach ($this->images as $image):


// set the dimensions according to your layout
$imgWidth = 100;
$imgHeight = $this->imgHeight;

if (empty($imgWidth)) {
	$imgWidth = 172;
}

// get dimensions of original file
$img = 'application/data/media/'.$image->idart.'/'.$image->mediaid.'.'.$image->extension;
$imgDim = getimagesize($img);

if ($imgWidth >= $imgHeight) {
	// constant width
	$factor = $imgWidth/$imgDim[0];
	$imgHeight = round($imgDim[1]*$factor);
} else {
	// constant height
	$factor = $imgHeight/$imgDim[1];
	$imgWidth = round($imgDim[0]*$factor);
}

// get alt-text for image
$alt = '';
if($image->name != '') {
    $alt = $image->name;
}
if($image->subline != '') {
    $alt .= ' '.$image->subline;
}
if($image->description != '') {
    $alt .= ' - '.$image->description;
}
?>
        
    <div class="item image_container<?php if($i == 0): ?> first<?php endif; ?>">
		<?php if(!empty($image->filename)): ?>
			<a href="/image/600/400/0/<?php echo $image->idart; ?>/<?php echo $image->filename; ?>" rel="gallery" title="<?php echo $alt;?>" class="big_image">
				<img src="/image/150/100/2/<?php echo $image->idart; ?>/<?php echo $image->filename; ?>" alt="<?php echo $alt; ?>" class="float_left"/>
			</a>
		<?php endif; ?>
        <p class="caption">
            <?php if(!empty($image->name)): ?><span class="name"><?php echo $image->name; ?></span><?php endif; ?>
            <?php if(!empty($image->subline)): ?><span class="subline"><?php echo $image->subline; ?></span><?php endif; ?>
        </p>
    </div>
    <?php $i++; ?>
<?php endforeach; ?>
</div>

<?php Aitsu_Util_Javascript::add("
$(document).ready(function() {
    $('.image_list .caption').css({top:'130px', opacity:0, display:'none'});
    $('.image_list a').mouseover(function(){
        $(this).next('.caption').css({display:'block'}).animate({top:'100px',opacity:1}, 250).children('.name').hide().slideDown(500);
    })
    $('.image_list .item').mouseleave(function(){
        $('.caption').css({opacity:0, top:'80px', display:'none'});
    });

    $('a[rel=gallery]').fancybox({
        'transitionIn'		: 'none',
        'transitionOut'		: 'none',
        'titlePosition' 	: 'inside',
        'overlayColor'      : '#FFF',
        'titleFormat'		: function(title, currentArray, currentIndex, currentOpts) {
            return '<span id=\"fancybox-title-over\">Bild ' + (currentIndex + 1) + ' / ' + currentArray.length + (title.length ? ' &nbsp; ' + title : '') + '</span>';
        }
    });
});
"); ?>