<!-- einfaches Bild im Text (standard) -->
<?php
//$image = $this->images[0];

// set the dimensions according to your layout
$imgWidth = $this->imgWidth;
$imgHeight = $this->imgHeight;

if (empty($imgWidth)) {
	$imgWidth = 270;
}
$i = 1;
?>

<?php if(count($this->images) > 1 || $this->layout == 'block'): ?><div class="image_container block"><?php endif; ?>

<?php foreach ($this->images as $image):
    // get dimensions of original file
    $img = 'application/data/media/'.$image->idart.'/'.$image->mediaid.'.'.$image->extension;
    $imgDim = getimagesize($img);

    if ($imgWidth >= $imgHeight) {
        // constant width
        $factor = $imgWidth/$imgDim[0];
        $imgHeight = round($imgDim[1]*$factor);
    } else {
        // constant height
        $factor = $imgHeight/$imgDim[1];
        $imgWidth = round($imgDim[0]*$factor);
    }

    // get alt-text for image
    $alt = $image->filename;
    if($image->description != '') {
        $alt = $image->description;
    } elseif($image->subline != '') {
        $alt = $image->subline;
    } elseif($image->name != '') {
        $alt = $image->name;
    }
    ?>

    <?php if($this->layout == 'center'):?><span class="image center"><?php endif; ?>
        <?php if(!empty($this->href)): ?><a href="<?php echo $this->href; ?>"<?php if(!empty($this->target)): ?> target="<?php echo $this->target; ?>"<?php endif; ?>><?php endif; ?>
            <img src="/image/<?php echo $imgWidth; ?>/<?php echo $imgHeight; ?>/2/<?php echo $image->idart; ?>/<?php echo $image->filename; ?>" alt="<?php echo $alt; ?>" width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>" class="image<?php if($this->layout == 'left' || $this->layout == 'right'):?> float_<?php echo $this->layout;?><?php endif; ?><?php if(count($this->images) == $i): ?> last<?php endif; ?>"/>
        <?php if(!empty($this->href)) echo '</a>'; ?>
    <?php if($this->layout == 'center'):?></span><?php endif; ?>
    <?php $i++; ?>
<?php endforeach; ?>
<?php if(count($this->images) > 1 || $this->layout == 'block'): ?></div><?php endif; ?>