<!-- Team/Portraits -->
<div class="image_list team">
<?php
foreach ($this->images as $image):


// set the dimensions according to your layout
$imgWidth = 100;
$imgHeight = 0;

// get dimensions of original file
$img = 'application/data/media/'.$image->idart.'/'.$image->mediaid.'.'.$image->extension;
$imgDim = getimagesize($img);

if ($imgWidth >= $imgHeight) {
	// constant width
	$factor = $imgWidth/$imgDim[0];
	$imgHeight = round($imgDim[1]*$factor);
} else {
	// constant height
	$factor = $imgHeight/$imgDim[1];
	$imgWidth = round($imgDim[0]*$factor);
}

// get alt-text for image
$alt = $image->filename;
if($image->name != '') {
    $alt = $image->name;
}
if($image->subline != '') {
    $alt .= ', '.$image->subline;
}
if($image->description != '') {
    $alt .= ' - '.$image->description;
}
?>
    <div class="item">
        <img src="/image/<?php echo $imgWidth; ?>/<?php echo $imgHeight; ?>/2/<?php echo $image->idart; ?>/<?php echo $image->filename; ?>" alt="<?php echo $alt; ?>" width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>" class="image float_left"/>
        <p class="caption">
            <?php if(!empty($image->name)): ?><span class="name"><?php echo $image->name; ?></span><?php endif; ?>
            <?php if(!empty($image->subline)): ?><span class="subline"><?php echo $image->subline; ?></span><?php endif; ?>
        </p>
    </div>
<?php endforeach; ?>
</div>
<?php Aitsu_Util_Javascript::add("
$(document).ready(function() {
    $('.team .caption').css({top:'130px', opacity:0, display:'none'});
    $('.team img').mouseover(function(){
        $(this).next('.caption').css({display:'block'}).animate({top:'150px',opacity:1}, 250).children('.name').hide().slideDown(500).next('.function').hide().slideDown(200);
    })
    $('.team .item').mouseleave(function(){
        $('.caption').css({opacity:0, top:'130px', display:'none'});
    });
});
"); ?>