<!-- News untereinander -->
<div class="news">
<?php foreach ($this->items as $index=>$article) : ?>
	<div class="item<?php if($index == 0):?> first<?php endif ?><?php if($index == count($this->items)-1):?> last<?php endif ?>">
		<h2 class="title"><?php if(isset($article->teasertitle)): ?><?php echo $article->teasertitle; ?><?php else: ?><?php echo $article->articletitle; ?><?php endif; ?></h2>
		<img src="/image/233/154/1/<?php echo $article->idart; ?>/<?php echo $article->image; ?>" alt="<?php echo $article->articletitle; ?>"/>
		<p><?php echo nl2br(htmlentities($article->summary, ENT_COMPAT, 'UTF-8')); ?>
        <?php if(unserialize($article->setlink)): ?>
            <a class="more" href="{ref:idart-<?php echo $article->idart; ?>}"><?php echo Aitsu_Translate::_("mehr..."); ?></a>
        <?php endif; ?>
        </p>
	</div>
<?php endforeach; ?>
</div>