<!-- News in der Hauptspalte untereinander -->
<div class="news aktuell">
<?php foreach ($this->items as $index=>$article) : ?>
	<div class="item<?php if($index == 0):?> first<?php endif ?><?php if($index == count($this->items)-1):?> last<?php endif ?>">
			<p class="publish date">
				<?php if(!empty($article->pubfrom)): ?>
					<?php echo date("d.m.Y", strtotime($article->pubfrom)); ?>
				<?php elseif(!empty($article->created)): ?>
					<?php echo date("d.m.Y", strtotime($article->created)); ?>
				<?php endif; ?>
			</p>
		<h2 class="title"><?php if(unserialize($article->setlink)): ?><a class="more" title="<?php if(isset($article->teasertitle)): ?><?php echo $article->teasertitle; ?><?php else: ?><?php echo $article->articletitle; ?><?php endif; ?>" href="{ref:idart-<?php echo $article->idart; ?>}"><?php endif; ?><?php if(isset($article->teasertitle)): ?><?php echo $article->teasertitle; ?><?php else: ?><?php echo $article->articletitle; ?><?php endif; ?><?php if(unserialize($article->setlink)): ?></a><?php endif; ?></h2>
		<?php if(!empty($article->image)): ?>

            <?php if(unserialize($article->setlink)): ?><a title="<?php if(isset($article->teasertitle)): ?><?php echo $article->teasertitle; ?><?php else: ?><?php echo $article->articletitle; ?><?php endif; ?>" href="{ref:idart-<?php echo $article->idart; ?>}"><?php endif; ?>
            <img src="/image/233/154/2/<?php echo $article->idart; ?>/<?php echo $article->image; ?>" alt="<?php echo $article->articletitle; ?>"/>
            <?php if(unserialize($article->setlink)): ?></a><?php endif; ?>
        <?php endif; ?>
		<p><?php echo nl2br(htmlentities($article->summary, ENT_COMPAT, 'UTF-8')); ?>
        <?php if(unserialize($article->setlink)): ?>
            <br/><a class="more" title="<?php if(isset($article->teasertitle)): ?><?php echo $article->teasertitle; ?><?php else: ?><?php echo $article->articletitle; ?><?php endif; ?>" href="{ref:idart-<?php echo $article->idart; ?>}"><?php echo Aitsu_Translate::_("mehr..."); ?></a>
        <?php endif; ?>
        </p>
	</div>
<?php endforeach; ?>
</div>